
try {
    let x = noExiste()
} catch (error) {
    alert (error)
}
